name: hugo

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: git submodule init
    - run: git submodule update
    - run: mkdir -p ./public
    - name: build
      uses: peaceiris/actions-hugo@v2
    - run: touch ./public/.nojekyll
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

